### ISSUE TITLE
Data truncated

### ISSUE THREAD

**Issue by dsrukmana** [rnaby/tCableBilling#5]
When I try to insert new client data I get this message:

```
 Illuminate \ Database \ QueryException (01000)
SQLSTATE[01000]: Warning: 1265 Data truncated for column 'address_proof' at row 1 (SQL: insert into `clients` (`area_id`, `name`, `phone_no_1`, `phone_no_2`, `address`, `connection_type`, `package_id`, `address_proof`, `client_status`, `address_proof_no`, `device_box_no`, `updated_at`, `created_at`)
```

Am I doing something wrong?

**Comment by deveshg169** [comment]
you have to fill data base in proper way..

i have one issue can you drop me your contact details on deveshg169@gmail.com

**Comment by khanrn** [comment]
Thanks for your input. Anyway, currently a planning on a huge refactor is going on. Hopefully with in a short period you'll be notified about the future development plans of tCableBilling. Until then please please bear with us.

Thanks again.

**Comment by dsrukmana** [comment]
Thanks for response, I already figured out. And there's another issue I found on 'invalid datetime format' when trying to pass form data to database. I'm using MySQL so maybe SQLite default datetime format is diffferent with MySQL. @codemascot glad to hear this Project still alive and going to have an update in near future. This Project is awesome and very useful

**Comment by dsrukmana** [comment]
If I may add suggestion for fututre updates: Add note on the payment form and include on pdf output would be very useful.
