### ISSUE TITLE
User database issue

### ISSUE THREAD

**Issue by webmaster1264** [rnaby/tCableBilling#6]
I am not able to login as a user, manager or admin after creating user database in mysql please help

Thanks in Advance.

**Comment by khanrn** [comment]
You've to seed the DB. I recommend you to do a little research on seeding the database for a Laravel app. You can also have a look at [this](https://github.com/tcablebilling/tCableBilling/blob/master/database/seeds/TCableBilling/UserTableSeeder.php) file.
